### ISSUE TITLE
MELPA recipe?

### ISSUE THREAD

**Issue by grettke** [zk-phi/spray#1]
Hi,

Just wondering if you have stated to create a MELPA recipe?

Nice distribution vehicle.

Kind regards,

gcr

**Comment by erikcw** [comment]
Here is the local recipe I'm using for el-get

`spray.rcp`

``` el
(:name spray
        :description "[Emacs] an elisp implementation of OpenSpritz"
        :type github
        :pkgname "zk-phi/spray")
```

**Comment by grettke** [comment]
Thank you. I will set up a MELPA recipe too.
