### ISSUE TITLE
Center spray text in buffer?

### ISSUE THREAD

**Issue by erikcw** [zk-phi/spray#2]
It would be great to be able to center the spray text in the buffer.

**Comment by zk-phi** [comment]
Since the width of spray text is not always the same, it's hard to keep the text centered whilst the ORP (the red colored character) position is also fixed. But it's not very difficult to add a constant-width margin before the leftmost character. Does it seem useful?

**Comment by erikcw** [comment]
Yeah -- I think that would do the trick.

Is it also possible to add some margin above the text so it gets pushed down just a bit?

**Comment by zk-phi** [comment]
margins left/above the spray text are both implemented. thanks for the ideas.
