### ISSUE TITLE
Release a stable version

### ISSUE THREAD

**Issue by vinipsmaker** [zk-phi/spray#6]
The [new home](https://github.com/ian-kelling/spray) banned bug tracking, then I'm reporting here.

The project is great, but it should release a stable version, so it distro packagers can create packages for spray.

**Comment by ian-kelling** [comment]
Thanks. I didn't realize the other repo didn't have bug tracking on. I will fix that. Also, is there any specific steps you would recommend to mark a version as stable? Off the top of my head, we can tag a release, and make a note in the elisp headers.

**Comment by vinipsmaker** [comment]
I usually do exactly what you proposed (add release notes on some file from the repo and then tag the release), but a lot of project like to prefix the tag name with the string `v` (e.g. `v0.1`).

[Semantic Versioning](http://semver.org/) is also a good idea.

**Comment by zk-phi** [comment]
the project seems now moved to https://gitlab.com/iankelling/spray.
closing.
